apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelappdeployment-prod
  labels:
    app: {{ .Values.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.app }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
          - containerPort: 8080
        env:
        - name: NSKEY
          value: {{ .Values.nsKey }}
        - name: DARKKEY
          value: {{ .Values.darkKey }}
