kind: Service
apiVersion: v1
metadata:
  name: redirect
spec:
  type: NodePort
  selector:
    app: {{ .Values.selectApp }}
  ports:
  - name: https-port
    protocol: TCP
    port: 80
    nodePort: 30001
